url: "kanenstephens.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "kanenstephens" # the name of your site, e.g. ACME Corp.
author: "kanen stephens"

exclude:
    - LICENSE
    - README.md

collections_dir: _collections

collections:
    life-a-real-thing:
        output: true
        # permalink: /books/:collection/:title
    posts:
        output: true
        permalink: /:categories/:title
# description: >- # this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
